version: "3"
services:
  pysen_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: pysen_sample-image
    container_name: pysen_sample-container
    tty: true
